// Auto-generated by vite-plugin-modal-types
export const MODALS = {
  /** 
   * @source src/components/modals/ApproveInvoiceWithCsiModal.mdl.vue
   */
  ApproveInvoiceWithCsiModal: 'ApproveInvoiceWithCsiModal',
  /** 
   * @source src/components/modals/ChangePasswordModal.mdl.vue
   */
  ChangePasswordModal: 'ChangePasswordModal',
  /** 
   * @source src/components/modals/CollectModal.mdl.vue
   */
  CollectModal: 'CollectModal',
  /** 
   * @source src/components/modals/ConfirmationModal.mdl.vue
   */
  ConfirmationModal: 'ConfirmationModal',
  /** 
   * @source src/components/modals/FileViewerModal.mdl.vue
   */
  FileViewerModal: 'FileViewerModal',
  /** 
   * @source src/components/modals/ReasonModal.mdl.vue
   */
  ReasonModal: 'ReasonModal',
  /** 
   * @source src/components/modals/RejectReasonModal.mdl.vue
   */
  RejectReasonModal: 'RejectReasonModal',
  /** 
   * @source src/components/modals/StatusChangeModal.mdl.vue
   */
  StatusChangeModal: 'StatusChangeModal',
  /** 
   * @source src/components/modals/VoucherModal.mdl.vue
   */
  VoucherModal: 'VoucherModal',
  /** 
   * @source src/components/modals/tyreModals/AssignTyreHandoff.mdl.vue
   */
  AssignTyreHandoff: 'AssignTyreHandoff',
  /** 
   * @source src/components/modals/tyreModals/CompleteTyreInstallModal.mdl.vue
   */
  CompleteTyreInstallModal: 'CompleteTyreInstallModal',
  /** 
   * @source src/components/modals/tyreModals/CompleteTyreReturnModal.mdl.vue
   */
  CompleteTyreReturnModal: 'CompleteTyreReturnModal',
  /** 
   * @source src/components/modals/tyreModals/CompleteTyreTransferModal.mdl.vue
   */
  CompleteTyreTransferModal: 'CompleteTyreTransferModal',
  /** 
   * @source src/components/modals/tyreModals/Decommission.mdl.vue
   */
  Decommission: 'Decommission',
  /** 
   * @source src/components/modals/tyreModals/Inspect.mdl.vue
   */
  Inspect: 'Inspect',
  /** 
   * @source src/components/modals/tyreModals/Reassign.mdl.vue
   */
  Reassign: 'Reassign',
  /** 
   * @source src/components/modals/tyreModals/RemoveFromVehicle.mdl.vue
   */
  RemoveFromVehicle: 'RemoveFromVehicle',
  /** 
   * @source src/components/modals/tyreModals/Repair.mdl.vue
   */
  Repair: 'Repair',
  /** 
   * @source src/components/modals/tyreModals/Replace.mdl.vue
   */
  Replace: 'Replace',
  /** 
   * @source src/components/modals/tyreModals/Rethread.mdl.vue
   */
  Rethread: 'Rethread',
  /** 
   * @source src/components/modals/tyreModals/Rotate.mdl.vue
   */
  Rotate: 'Rotate',
  /** 
   * @source src/modules/admin/modals/CityModal.mdl.vue
   */
  CityModal: 'CityModal',
  /** 
   * @source src/modules/admin/modals/CreateCarrierAdminModal.mdl.vue
   */
  CreateCarrierAdminModal: 'CreateCarrierAdminModal',
  /** 
   * @source src/modules/admin/modals/CreateShipperAdminModal.mdl.vue
   */
  CreateShipperAdminModal: 'CreateShipperAdminModal',
  /** 
   * @source src/modules/admin/modals/EditCarrierAdminModal.mdl.vue
   */
  EditCarrierAdminModal: 'EditCarrierAdminModal',
  /** 
   * @source src/modules/admin/modals/EditShipperAdminModal.mdl.vue
   */
  EditShipperAdminModal: 'EditShipperAdminModal',
  /** 
   * @source src/modules/admin/modals/GpsProviderModal.mdl.vue
   */
  GpsProviderModal: 'GpsProviderModal',
  /** 
   * @source src/modules/admin/modals/InvoiceTermsModal.mdl.vue
   */
  InvoiceTermsModal: 'InvoiceTermsModal',
  /** 
   * @source src/modules/admin/modals/PlanChangeModal.mdl.vue
   */
  PlanChangeModal: 'PlanChangeModal',
  /** 
   * @source src/modules/admin/modals/PricingPlanModal.mdl.vue
   */
  PricingPlanModal: 'PricingPlanModal',
  /** 
   * @source src/modules/admin/modals/RaiseInvoiceModal.mdl.vue
   */
  RaiseInvoiceModal: 'RaiseInvoiceModal',
  /** 
   * @source src/modules/admin/modals/RecordPaymentModal.mdl.vue
   */
  RecordPaymentModal: 'RecordPaymentModal',
  /** 
   * @source src/modules/admin/modals/SlotChangeModal.mdl.vue
   */
  SlotChangeModal: 'SlotChangeModal',
  /** 
   * @source src/modules/admin/modals/SubscriptionModuleModal.mdl.vue
   */
  SubscriptionModuleModal: 'SubscriptionModuleModal',
  /** 
   * @source src/modules/admin/modals/TmsModuleModal.mdl.vue
   */
  TmsModuleModal: 'TmsModuleModal',
  /** 
   * @source src/modules/fleet/modals/VoidEntryModal.mdl.vue
   */
  VoidEntryModal: 'VoidEntryModal',
  /** 
   * @source src/modules/operation/components/modals/AddAdvanceModal.mdl.vue
   */
  AddAdvanceModal: 'AddAdvanceModal',
  /** 
   * @source src/modules/operation/components/modals/AddAdvanceStandaloneModal.mdl.vue
   */
  AddAdvanceStandaloneModal: 'AddAdvanceStandaloneModal',
  /** 
   * @source src/modules/operation/components/modals/AddCustomerModal.mdl.vue
   */
  AddCustomerModal: 'AddCustomerModal',
  /** 
   * @source src/modules/operation/components/modals/AddInfractionModal.mdl.vue
   */
  AddInfractionModal: 'AddInfractionModal',
  /** 
   * @source src/modules/operation/components/modals/AddInsuranceModal.mdl.vue
   */
  AddInsuranceModal: 'AddInsuranceModal',
  /** 
   * @source src/modules/operation/components/modals/AddLeasedVehicleModal.mdl.vue
   */
  AddLeasedVehicleModal: 'AddLeasedVehicleModal',
  /** 
   * @source src/modules/operation/components/modals/AddPrePaymentModal.mdl.vue
   */
  AddPrePaymentModal: 'AddPrePaymentModal',
  /** 
   * @source src/modules/operation/components/modals/AddPrePaymentStandaloneModal.mdl.vue
   */
  AddPrePaymentStandaloneModal: 'AddPrePaymentStandaloneModal',
  /** 
   * @source src/modules/operation/components/modals/AddSettlementModal.mdl.vue
   */
  AddSettlementModal: 'AddSettlementModal',
  /** 
   * @source src/modules/operation/components/modals/AddVehicleDamageModal.mdl.vue
   */
  AddVehicleDamageModal: 'AddVehicleDamageModal',
  /** 
   * @source src/modules/operation/components/modals/AdjustInitialSettlementBalanceModal.mdl.vue
   */
  AdjustInitialSettlementBalanceModal: 'AdjustInitialSettlementBalanceModal',
  /** 
   * @source src/modules/operation/components/modals/AdjustmentRequestModal.mdl.vue
   */
  AdjustmentRequestModal: 'AdjustmentRequestModal',
  /** 
   * @source src/modules/operation/components/modals/ApprovalModal.mdl.vue
   */
  ApprovalModal: 'ApprovalModal',
  /** 
   * @source src/modules/operation/components/modals/ApproveStoreRequisitionModal.mdl.vue
   */
  ApproveStoreRequisitionModal: 'ApproveStoreRequisitionModal',
  /** 
   * @source src/modules/operation/components/modals/BatchAddInsuranceModal.mdl.vue
   */
  BatchAddInsuranceModal: 'BatchAddInsuranceModal',
  /** 
   * @source src/modules/operation/components/modals/CancelInsurancePaymentModal.mdl.vue
   */
  CancelInsurancePaymentModal: 'CancelInsurancePaymentModal',
  /** 
   * @source src/modules/operation/components/modals/CarrierUserModal.mdl.vue
   */
  CarrierUserModal: 'CarrierUserModal',
  /** 
   * @source src/modules/operation/components/modals/CompleteWorkOrderModal.mdl.vue
   */
  CompleteWorkOrderModal: 'CompleteWorkOrderModal',
  /** 
   * @source src/modules/operation/components/modals/ContactModal.mdl.vue
   */
  ContactModal: 'ContactModal',
  /** 
   * @source src/modules/operation/components/modals/ContractRouteAddModal.mdl.vue
   */
  ContractRouteAddModal: 'ContractRouteAddModal',
  /** 
   * @source src/modules/operation/components/modals/ContractRouteEditModal.mdl.vue
   */
  ContractRouteEditModal: 'ContractRouteEditModal',
  /** 
   * @source src/modules/operation/components/modals/DamageReportModal.mdl.vue
   */
  DamageReportModal: 'DamageReportModal',
  /** 
   * @source src/modules/operation/components/modals/EditDriverStatusModal.mdl.vue
   */
  EditDriverStatusModal: 'EditDriverStatusModal',
  /** 
   * @source src/modules/operation/components/modals/EditExpiryDateModal.mdl.vue
   */
  EditExpiryDateModal: 'EditExpiryDateModal',
  /** 
   * @source src/modules/operation/components/modals/EditInsuranceModal.mdl.vue
   */
  EditInsuranceModal: 'EditInsuranceModal',
  /** 
   * @source src/modules/operation/components/modals/EditLeasedVehicleModal.mdl.vue
   */
  EditLeasedVehicleModal: 'EditLeasedVehicleModal',
  /** 
   * @source src/modules/operation/components/modals/ExtendLeaseModal.mdl.vue
   */
  ExtendLeaseModal: 'ExtendLeaseModal',
  /** 
   * @source src/modules/operation/components/modals/FacilityModal.mdl.vue
   */
  FacilityModal: 'FacilityModal',
  /** 
   * @source src/modules/operation/components/modals/GoodTransferModal.mdl.vue
   */
  GoodTransferModal: 'GoodTransferModal',
  /** 
   * @source src/modules/operation/components/modals/InventoryBatchModal.mdl.vue
   */
  InventoryBatchModal: 'InventoryBatchModal',
  /** 
   * @source src/modules/operation/components/modals/InventoryCategoryModal.mdl.vue
   */
  InventoryCategoryModal: 'InventoryCategoryModal',
  /** 
   * @source src/modules/operation/components/modals/InventoryItemModal.mdl.vue
   */
  InventoryItemModal: 'InventoryItemModal',
  /** 
   * @source src/modules/operation/components/modals/InventorySerialModal.mdl.vue
   */
  InventorySerialModal: 'InventorySerialModal',
  /** 
   * @source src/modules/operation/components/modals/InventoryVendorModal.mdl.vue
   */
  InventoryVendorModal: 'InventoryVendorModal',
  /** 
   * @source src/modules/operation/components/modals/InvoiceLineGroupsModal.mdl.vue
   */
  InvoiceLineGroupsModal: 'InvoiceLineGroupsModal',
  /** 
   * @source src/modules/operation/components/modals/ItemGroupModal.mdl.vue
   */
  ItemGroupModal: 'ItemGroupModal',
  /** 
   * @source src/modules/operation/components/modals/MarkAsPaidModal.mdl.vue
   */
  MarkAsPaidModal: 'MarkAsPaidModal',
  /** 
   * @source src/modules/operation/components/modals/OnboardingCelebrationModal.mdl.vue
   */
  OnboardingCelebrationModal: 'OnboardingCelebrationModal',
  /** 
   * @source src/modules/operation/components/modals/PurchaseOrderModal.mdl.vue
   */
  PurchaseOrderModal: 'PurchaseOrderModal',
  /** 
   * @source src/modules/operation/components/modals/PurchaseRequisitionModal.mdl.vue
   */
  PurchaseRequisitionModal: 'PurchaseRequisitionModal',
  /** 
   * @source src/modules/operation/components/modals/RejectInfractionModal.mdl.vue
   */
  RejectInfractionModal: 'RejectInfractionModal',
  /** 
   * @source src/modules/operation/components/modals/RenewLeaseModal.mdl.vue
   */
  RenewLeaseModal: 'RenewLeaseModal',
  /** 
   * @source src/modules/operation/components/modals/ReverseAdjustmentModal.mdl.vue
   */
  ReverseAdjustmentModal: 'ReverseAdjustmentModal',
  /** 
   * @source src/modules/operation/components/modals/SelectShipmentModal.mdl.vue
   */
  SelectShipmentModal: 'SelectShipmentModal',
  /** 
   * @source src/modules/operation/components/modals/StoreRequisitionModal.mdl.vue
   */
  StoreRequisitionModal: 'StoreRequisitionModal',
  /** 
   * @source src/modules/operation/components/modals/SwapDriversModal.mdl.vue
   */
  SwapDriversModal: 'SwapDriversModal',
  /** 
   * @source src/modules/operation/components/modals/UserResetPassword.mdl.vue
   */
  UserResetPassword: 'UserResetPassword',
  /** 
   * @source src/modules/operation/components/modals/VehicleFuelUsageModal.mdl.vue
   */
  VehicleFuelUsageModal: 'VehicleFuelUsageModal',
  /** 
   * @source src/modules/operation/components/modals/VehicleGoalModal.mdl.vue
   */
  VehicleGoalModal: 'VehicleGoalModal',
  /** 
   * @source src/modules/operation/components/modals/VehicleMapModal.mdl.vue
   */
  VehicleMapModal: 'VehicleMapModal',
  /** 
   * @source src/modules/operation/components/modals/VehicleProductivityKpiModal.mdl.vue
   */
  VehicleProductivityKpiModal: 'VehicleProductivityKpiModal',
  /** 
   * @source src/modules/operation/components/modals/VehicleShipmentFinancialKpiModal.mdl.vue
   */
  VehicleShipmentFinancialKpiModal: 'VehicleShipmentFinancialKpiModal',
  /** 
   * @source src/modules/operation/modals/AddTransporterModal.mdl.vue
   */
  AddTransporterModal: 'AddTransporterModal',
  /** 
   * @source src/modules/operation/modals/AddVehicleRegistrationModal.mdl.vue
   */
  AddVehicleRegistrationModal: 'AddVehicleRegistrationModal',
  /** 
   * @source src/modules/operation/modals/EditVehicleStatusModal.mdl.vue
   */
  EditVehicleStatusModal: 'EditVehicleStatusModal',
  /** 
   * @source src/modules/operation/modals/VehicleRegistrationTypeModal.mdl.vue
   */
  VehicleRegistrationTypeModal: 'VehicleRegistrationTypeModal',
  /** 
   * @source src/modules/shipper/components/modals/AnnouncementModal.mdl.vue
   */
  AnnouncementModal: 'AnnouncementModal',
  /** 
   * @source src/modules/shipper/components/modals/CommodityModal.mdl.vue
   */
  CommodityModal: 'CommodityModal',
  /** 
   * @source src/modules/shipper/components/modals/CreateCityShipperCodeModal.mdl.vue
   */
  CreateCityShipperCodeModal: 'CreateCityShipperCodeModal',
  /** 
   * @source src/modules/shipper/components/modals/EditCityShipperCodeModal.mdl.vue
   */
  EditCityShipperCodeModal: 'EditCityShipperCodeModal',
  /** 
   * @source src/modules/shipper/components/modals/PackagingModal.mdl.vue
   */
  PackagingModal: 'PackagingModal',
  /** 
   * @source src/modules/shipper/components/modals/PayInvoiceModal.mdl.vue
   */
  PayInvoiceModal: 'PayInvoiceModal',
  /** 
   * @source src/modules/shipper/components/modals/RoleModal.mdl.vue
   */
  RoleModal: 'RoleModal',
  /** 
   * @source src/modules/shipper/components/modals/ShipperUserModal.mdl.vue
   */
  ShipperUserModal: 'ShipperUserModal',
};
