import ModalParent from "./ModalParent.vue"
import { useModal, setModalConfig, getModalConfig } from "./store/modal"
import modal from "./plugins/modal"

/**
 * Opens a modal component and returns a promise that resolves when the modal is closed.
 *
 * @param {string} modalToOpen - The identifier(name of the modal file) of the modal component to open.
 * @param {Object} [data] - Optional data to pass to the modal component.
 * @param {Function} [cb] - Optional callback function to be executed after the modal is closed.
 * @param {Object} options - Optional options
 * @returns {Promise<any>} A promise that resolves with the response from the modal.
 */
function openModal(modalToOpen, data, cb, options) {
  const { openModal: OM } = useModal();
  return OM(modalToOpen, data, cb, options);
}

/**
 * Closes an open modal component.
 *
 * @param {*} [response] - Optional response data to send back from the modal.
 * @param {boolean} [sendResponse=true] - Optional flag to determine whether to send the response data. Defaults to true.
 * @returns {void}
 */
function closeModal(response = false, sendResponse = true) {
  const { closeModal: CM } = useModal();
  return CM(response, sendResponse);
}

/**
 * Closes the topmost modal WITHOUT running its beforeClose guard.
 *
 * @param {*} [response] - Optional response data to send back from the modal.
 * @param {boolean} [sendResponse=true]
 * @returns {Promise<boolean>}
 */
function forceCloseModal(response = false, sendResponse = true) {
  const { forceCloseModal: FC } = useModal();
  return FC(response, sendResponse);
}

/**
 * Registers a beforeClose guard on the current topmost modal. Call during the
 * modal content's setup. `fn` returns boolean | Promise<boolean> (true = allow
 * the close). Runs for every close path: X, overlay, ESC, browser Back, and
 * programmatic close. Returns an unregister function.
 *
 * @param {(response?: any) => boolean | Promise<boolean>} fn
 * @returns {() => void}
 */
function onBeforeModalClose(fn) {
  const { onBeforeModalClose: OB } = useModal();
  return OB(fn);
}

/**
 * Retrieves a modal component instance by its name.
 *
 * @param {string} name - The name or identifier of the modal component to retrieve.
 * @returns {any} - The instance of the modal component identified by the name.
 */
function getModal(name) {
  const { getModal: GM } = useModal();
  return GM(name);
}

// Export MODALS constant for autocomplete (generated by plugin)
import * as enums from './FileNameEnums';
const MODALS = enums.MODALS || {};

// Dirty-diff helpers + the core (router-free) close guard.
import { normalizeForCompare, hashForCompare, isDirty } from './dirty.js';
import { useCloseGuard } from './guards/useCloseGuard.js';

// Export the functions
export {
  openModal,
  closeModal,
  forceCloseModal,
  onBeforeModalClose,
  getModal,
  useModal,
  ModalParent,
  MODALS,
  useCloseGuard,
  normalizeForCompare,
  hashForCompare,
  isDirty,
  setModalConfig,
  getModalConfig
};

export default modal