import ModalParent from "./ModalParent.vue"
import { useModal } from "./store/modal"
import modal from "./plugins/modal"

/**
 * Opens a modal component and returns a promise that resolves when the modal is closed.
 *
 * @param {string} modalToOpen - The identifier(name of the modal file) of the modal component to open.
 * @param {Object} [data] - Optional data to pass to the modal component.
 * @param {Function} [cb] - Optional callback function to be executed after the modal is closed.
 * @param {Object} options - Optional options
 * @returns {Promise<any>} A promise that resolves with the response from the modal.
 */
function openModal(modalToOpen, data, cb, options) {
  const { openModal: OM } = useModal();
  return OM(modalToOpen, data, cb, options);
}

/**
 * Closes an open modal component.
 *
 * @param {*} [response] - Optional response data to send back from the modal.
 * @param {boolean} [sendResponse=true] - Optional flag to determine whether to send the response data. Defaults to true.
 * @returns {void}
 */
function closeModal(response = false, sendResponse = true) {
  const { closeModal: CM } = useModal();
  CM(response, sendResponse);
}

/**
 * Retrieves a modal component instance by its name.
 *
 * @param {string} name - The name or identifier of the modal component to retrieve.
 * @returns {any} - The instance of the modal component identified by the name.
 */
function getModal(name) {
  const { getModal: GM } = useModal();
  return GM(name);
}

// Export MODALS constant for autocomplete (generated by plugin)
import * as enums from './FileNameEnums';
const MODALS = enums.MODALS || {};

// Export the functions
export {
  openModal,
  closeModal,
  getModal,
  useModal,
  ModalParent,
  MODALS
};

export default modal